version: '3.8'

services:
  app:
    image: farm-project:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: farm-app
    restart: unless-stopped
    ports:
      - "8004:80"
    environment:
      APP_NAME: "${APP_NAME:-Mehmood Cattle and Dairy Farm}"
      APP_ENV: "${APP_ENV:-production}"
      APP_KEY: "${APP_KEY}"
      APP_DEBUG: "${APP_DEBUG:-false}"
      APP_URL: "${APP_URL}"
      APP_TIMEZONE: "${APP_TIMEZONE:-UTC}"
      
      DB_CONNECTION: "${DB_CONNECTION:-mysql}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT:-3306}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      
      BROADCAST_CONNECTION: "${BROADCAST_CONNECTION:-log}"
      FILESYSTEM_DISK: "${FILESYSTEM_DISK:-local}"
      QUEUE_CONNECTION: "${QUEUE_CONNECTION:-sync}"
      
      SESSION_DRIVER: "file"
      SESSION_LIFETIME: "${SESSION_LIFETIME:-120}"

      CACHE_STORE: "file"
      
      MEMCACHED_HOST: "${MEMCACHED_HOST:-127.0.0.1}"
      
      REDIS_HOST: "${REDIS_HOST:-127.0.0.1}"
      REDIS_PASSWORD: "${REDIS_PASSWORD:-null}"
      REDIS_PORT: "${REDIS_PORT:-6379}"
      
      MAIL_MAILER: "${MAIL_MAILER:-log}"
      MAIL_HOST: "${MAIL_HOST:-127.0.0.1}"
      MAIL_PORT: "${MAIL_PORT:-2525}"
      MAIL_USERNAME: "${MAIL_USERNAME:-null}"
      MAIL_PASSWORD: "${MAIL_PASSWORD:-null}"
      MAIL_ENCRYPTION: "${MAIL_ENCRYPTION:-null}"
      MAIL_FROM_ADDRESS: "${MAIL_FROM_ADDRESS:-hello@example.com}"
      MAIL_FROM_NAME: "${MAIL_FROM_NAME:-${APP_NAME}}"
    networks:
      - farm-network

networks:
  farm-network:
    driver: bridge
