[phases.setup]
nixPkgs = [
    "php84",
    "php84Extensions.gd",
    "php84Extensions.intl",
    "php84Extensions.zip",
    "php84Extensions.bcmath",
    "php84Extensions.pdo_mysql",
    "php84Extensions.exif",
    "php84Extensions.pcntl",
    "php84Extensions.opcache",
    "php84Extensions.mbstring",
    "php84Extensions.xml",
    "php84Extensions.curl",
    "php84Extensions.tokenizer",
    "php84Extensions.ctype",
    "php84Packages.composer",
    "nodejs_20"
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build",
    "chmod -R 775 storage bootstrap/cache"
]

[start]
cmd = "php artisan migrate --force && php artisan optimize && php artisan serve --host=0.0.0.0 --port=8004"
