# nixpacks.toml
[phases.setup]
nixPkgs = [
    "php82",
    "php82Packages.composer",
    "php82Extensions.pdo_mysql",
    "php82Extensions.gd",
    "php82Extensions.bcmath",
    "php82Extensions.zip",
    "php82Extensions.fileinfo",
    "php82Extensions.tokenizer",
    "php82Extensions.xml",
    "php82Extensions.curl",
    "php82Extensions.mbstring",
    "nodejs_20",
    "git"
]

[phases.build]
cmds = [
    "mkdir -p storage/framework/{sessions,views,cache}",
    "chmod -R 775 storage bootstrap/cache",
    "npm ci && npm run build",
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs",
    "php artisan storage:link --force"
]

[start]
cmd = "php artisan migrate --force && php artisan optimize && (php artisan queue:work &) && php artisan serve --host=0.0.0.0 --port=8002"